version: 2.1

commands:
  default-build-steps:
    steps:
      - checkout
      - run:
          name: Install
          command: |
            export DISPLAY=':99.0'
            Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
            npm ci || npm install
      - run:
          name: After Success
          command: npm run codecov

jobs:
  node_8:
    docker:
      - image: circleci/node:8
    steps:
      - default-build-steps
  
  node_10:
    docker:
      - image: circleci/node:10
    steps:
      - default-build-steps
  
  node_12:
    docker:
      - image: circleci/node:12
    steps:
      - default-build-steps

workflows:
  version: 2
  build:
    jobs:
      - node_8
      - node_10
      - node_12
