version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - install8
      - install10
      - install12
build_steps: &build_steps
    - run:
        name: Build
        command: |
            export DISPLAY=':99.0'
            Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
            npm ci || npm install
jobs:
  install8:
    docker:
      - image: node:8
    steps:
      - checkout
      - <<: *build_steps
  install10:
    docker:
      - image: node:10
    steps:
      - checkout
      - <<: *build_steps
  install12:
    docker:
      - image: node:12
    steps:
      - checkout
      - <<: *build_steps
