version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - install8:
      - install10:
      - install12:
		

jobs:
  install8:
    docker:
      - image: node:8
    steps:
      - checkout
      - run:
          name: run export 8
          command: export DISPLAY=':99.0'
      - run:
          name: run Xvfb 8
          command: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - run:
          name: run npm install script 8
          command: npm ci || npm install
      - run:
          name: success script 8
          command: npm run codecov
          when: on_success
  install10:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: run export 10
          command: export DISPLAY=':99.0'
      - run:
          name: run Xvfb 10
          command: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - run:
          name: run npm install script 10
          command: npm ci || npm install
      - run:
          name: success script 10
          command: npm run codecov
          when: on_success
  install12:
    docker:
      - image: node:12
    steps:
      - checkout
      - run:
          name: run export 12
          command: export DISPLAY=':99.0'
      - run:
          name: run Xvfb 12
          command: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - run:
          name: run npm install script 12
          command: npm ci || npm install
      - run:
          name: success script 12
          command: npm run codecov
          when: on_success
